### ISSUE TITLE
[HopeHub: Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#103]
**Task title**
Web app revision 

**Task description**
check for any missing details and fix it or enhance it

**Subtasks**

- [ ] Verify Paths
- [x] make Tab name
- [x] make tab icon
- [x] fix two clicks button issue
- [x] create a default image to replace unexistant pics, or ones haven't loaded yet
- [x] fix the space above the footer
- [x] fixx footer responsive on sm 
- [x] dark mode
- [x] check box color
- [x] default user/ hopehub image

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
