### ISSUE TITLE
[Blogs:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#104]
**Task title**
Blogs Revision

**Task description**
Fix the fetching of the blogs and the blogs carousel.

**Subtasks**
- [x] Fetch blogs on serverside in index.js and pass them to carousel component instead of useEffect
- [x] Fix BlogsCarousel
- [x] Fix blogs data on firestore
- [x] Fix admin blog post edit clear up
- [x] Fix h1, h2 tags, and lists rendering in the blogpage.

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
