### ISSUE TITLE
[Admin]

### ISSUE THREAD

**Issue by fketta** [202306-NEA-DZ-FEW/HopeHub#109]
**Task title**
Admin

**Task description**
Fix admin blogs & users section, and add features to it.

**Subtasks**
- [x] Ability to edit blog
- [x] Ability to delete blog
- [x] Ability to delete user
- [x] Reset blog input fields and unability to send if fields aren't filled
- [x] Set user data in the users collection upon signing up
