### ISSUE TITLE
HopeHub-RE

### ISSUE THREAD

**Issue by Zohir-kk** [202306-NEA-DZ-FEW/HopeHub#118]
**Task title**
HopeHub-RE

**Task description**

**Subtasks**
- [ ] Clean up firebase from unnecessary users 
- [ ] Create dummy users with dummy informations 
- [ ] Create dummy appointements with the users 

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
