### ISSUE TITLE
[Hopehub:re]

### ISSUE THREAD

**Issue by fketta** [202306-NEA-DZ-FEW/HopeHub#135]
**Task title**
General fixes in Hopehub

**Task description**
Overall fixing some issues that came with deployement

**Subtasks**
- [x] Fix responsiveness for footer
- [x] Adjust footer buttons
- [x] Fix responsiveness for about team cards
- [x] Adjust the booking an appointement buttons responsiveness
- [x] Fix drop down paths in therapy account
- [x] Fix redirection to the profile from the calendar in the booking
- [x] Fix therapist profile info not preloading
- [x] Fix pathname in Auth
- [x] Fix calendar responsiveness
- [x] Fix payment link to purchase ticket section
- [x] Add number of tickets left in booking step
- [x] Subtract a ticket once booking is done
- [x] Fix calendar dark mode
- [x] Fix logo in the browser tab (try svg instead of png, name all attached)
- [x] Add a loader for the video call
- [x] Right to left in arabic
- [x] Make the navbar fixed in small screeens
- [x] Block purchase tickets for therapists
- [x] Block the bio from expanding
- [ ] Fix dark mode toggle button
- [x] Fix dark mode connection section
- [ ] Optional: Add more tickets in the purchasing section PAGE
- [x] Fix social media links
- [x] Fix contact page dark mode
- [x] Put the newsletter component in the all blogs page
- [x] Revist translations
- [x] Revist padding in right to left

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
