### ISSUE TITLE
[Hopehub:re]

### ISSUE THREAD

**Issue by fketta** [202306-NEA-DZ-FEW/HopeHub#144]
**Task title**
Fixes for the deployed website

**Task description**
Implement some fixes for things that broke after deployement, or were missed during previous fixes.

**Subtasks**
- [x] Fix requirements page routing
- [x] BAA button in the tickets tab in dark mode
- [x] User not passed in the create therapist page
- [x] Default tab for admin dashboard
- [ ] Remove an extra alert from contact page

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
