### ISSUE TITLE
Booking page 

### ISSUE THREAD

**Issue by Zohir-kk** [202306-NEA-DZ-FEW/HopeHub#18]
# [Booking] #18

This pull request introduces changes related to the Contact page. It encompasses the following modifications:

- Created a Booking page styled it using Tailwind CSS.
- Developed a multi step form and devided it into components.
- Created a snapshot test for booking page and form components to ensure stability and reliability.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Files changed:

List of all file names created or modified (components, configs, style):

- Booking page (\src\pages\booking\index.jsx)
- booking components (src\components\booking)
- booking form tests (src\components\booking\__test__)

##Subtasks
- [x] General styling 
- [x] Making of the 8 steps form 
- [ ] Making the navigation between the form Cards 
- [ ] Translation 
- [x] Run tests for all components related

##Screenshots
![image](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/65735011/8b42b9cd-64b1-4114-9fae-947807e3e711)

##Link to the component on Figma
(https://www.figma.com/file/MhJAQ6EPFOUOp2CDYXgzlW/Hope-Hub?type=design&node-id=10650-293&mode=design&t=BU1XJH9ew5pA5cha-4)
