### ISSUE TITLE
login-signup

### ISSUE THREAD

**Issue by GhaniBahri** [202306-NEA-DZ-FEW/HopeHub#27]
**Task title**
login/signup page

**Task description**
to fix the previous issue 

**Subtasks**
- [x]  login UI
- [x] Sign up UI
- [x] forgot password UI
- [x] functionality with necessary configuration
- [ ] Facebook Auth
- [x] Google auth
- [x] add translation
