### ISSUE TITLE
[Stripe]

### ISSUE THREAD

**Issue by BrahimHM** [202306-NEA-DZ-FEW/HopeHub#36]
**Task title**
Stripe Implementation

**Task description**
Implement stripe and add card and payement functionality, linking it with firebase.

**Subtasks**
- [x] Set up stripe account
- [x] Link strip and firebase
- [x] Set up payement

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
