### ISSUE TITLE
add-users-to-firestore

### ISSUE THREAD

**Issue by GhaniBahri** [202306-NEA-DZ-FEW/HopeHub#44]
**Task title**
add users to firestore

**Task description**
implement necessary configuration to use additional user information in firestore

**Subtasks**
- [x] firestore for user sign up
- [x] firestore for therapist signup
- [x] get data after logging in
