### ISSUE TITLE
update user profile

### ISSUE THREAD

**Issue by GhaniBahri** [202306-NEA-DZ-FEW/HopeHub#47]
**Task title**
update user profile

**Task description**
allow users to update their profiles after registration, and upload their picures

**Subtasks**

- [ ] update email and passwword
- [x] update other infos in firestore
- [x] upload images
- [x] delete account option
- [x] fix the UI
