### ISSUE TITLE
[About:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#67]
**Task title**
about page enhancement & revision

**Task description**
Put the description here (Mandatory)

**Subtasks**

- [x] who we are title changing
- [x] the default button our team
- [x] the font size should be consistent
- [x] members Images 
- [x] buttons responsiveness
- [x] review all the page design and try to modify on it to improve it

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
