### ISSUE TITLE
[Loggin:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#69]
**Task title**
Email verification

**Task description**
when the user signs up, send a verification email

**Subtasks**

- [ ] verify gmail loggin
- [ ] After deployment add verification email
- [x] test therapist or user to direct him to the proper page update profile page
