### ISSUE TITLE
[Profile info:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#70]
**Task title**
enhancement and revision

**Task description**
Put the description here (Mandatory)

**Subtasks**

- [ ] Change upload id from image to text
- [ ] modify "security" word to change password
- [ ] update user info functionality should be revised
- [ ] responsiveness
- [ ] modify the title
- [ ] take the email from firebase user infos not from firestore
- [ ] show that the button is clicked and changes are saved

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
