### ISSUE TITLE
[Booking Appointment & Calendar:Re]

### ISSUE THREAD

**Issue by Amel7400** [202306-NEA-DZ-FEW/HopeHub#71]
**Task title**
enhancement and revision

**Task description**
Put the description here (Mandatory)

**Subtasks**

- [x] improving design
- [x] add all the dates to firebase and add the booked hours
- [x] tickets functionality
- [x] receive a confirmation email about booking an appointment
- [x] Calendar infos Therapist side
- [x] calendar toolbar responsiveness
- [x] forms background suggested to be white
- [x] work on form (qualities checklist) responsiveness
- [x] previous button select date
- [x] description step empty in small screens
- [x] select date list, calendar not responsive
- [x] after submission redirects to calendar
- [x]  Fix booking page check box, weird arabic sentence that comes out of nowhere.
- [x] For booking page, make text dynamic, based on wether we selected teen child, or adult.

**Screenshots**
Put at least one screenshot here

**Link to the component on Figma**
Put the link here
